services:
  - type: web
    name: flask-bursary
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --chdir /opt/render/project/src run:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: FLASK_APP
        value: run.py
      - key: FLASK_ENV
        value: production 