"""Add password reset fields

Revision ID: 5222711301e8
Revises: d67284031e9c
Create Date: 2024-12-06 18:45:27.229730

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "5222711301e8"
down_revision = "d67284031e9c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("password_reset_token", sa.String(length=100), nullable=True)
        )
        batch_op.add_column(
            sa.Column("password_reset_expires", sa.DateTime(), nullable=True)
        )
        batch_op.create_unique_constraint(None, ["password_reset_token"])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="unique")
        batch_op.drop_column("password_reset_expires")
        batch_op.drop_column("password_reset_token")

    # ### end Alembic commands ###
