"""initial migration

Revision ID: 7d12a93f664a
Revises: 
Create Date: 2024-12-04 11:34:46.405774

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d12a93f664a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Add unique constraint to student_id in academic_info
    op.create_unique_constraint('uq_academic_info_student_id', 'academic_info', ['student_id'])

    # Handle profile table changes
    with op.batch_alter_table('profile', schema=None) as batch_op:
        # First add id_number as nullable
        batch_op.add_column(sa.Column('id_number', sa.String(length=20), nullable=True))
    
    # Now that column exists, update the values
    op.execute("UPDATE profile SET id_number = 'LEGACY-' || id WHERE id_number IS NULL")
    
    # Make changes to profile table after update
    with op.batch_alter_table('profile', schema=None) as batch_op:
        # Make id_number not nullable
        batch_op.alter_column('id_number',
                            existing_type=sa.String(length=20),
                            nullable=False)
        
        # Add unique constraints
        batch_op.create_unique_constraint('uq_profile_phone_number', ['phone_number'])
        batch_op.create_unique_constraint('uq_profile_id_number', ['id_number'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profile', schema=None) as batch_op:
        batch_op.drop_constraint('uq_profile_id_number', type_='unique')
        batch_op.drop_constraint('uq_profile_phone_number', type_='unique')
        batch_op.drop_column('id_number')

    op.drop_constraint('uq_academic_info_student_id', 'academic_info', type_='unique')
    # ### end Alembic commands ###
