"""Add email verification fields

Revision ID: d67284031e9c
Revises: f8b6c530f55e
Create Date: 2024-12-05 23:23:13.008165

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "d67284031e9c"
down_revision = "f8b6c530f55e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.add_column(sa.Column("email_verified", sa.Boolean(), nullable=True))
        batch_op.add_column(
            sa.Column("email_verification_token", sa.String(length=100), nullable=True)
        )
        batch_op.add_column(
            sa.Column("email_verification_sent_at", sa.DateTime(), nullable=True)
        )
        batch_op.create_unique_constraint(None, ["email_verification_token"])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="unique")
        batch_op.drop_column("email_verification_sent_at")
        batch_op.drop_column("email_verification_token")
        batch_op.drop_column("email_verified")

    # ### end Alembic commands ###
