"""Add check constraints for phone and ID numbers

Revision ID: f8b6c530f55e
Revises: 446c45375786
Create Date: 2024-12-05 12:35:35.099956

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "f8b6c530f55e"
down_revision = "446c45375786"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("profile", schema=None) as batch_op:
        batch_op.alter_column(
            "phone_number",
            existing_type=sa.VARCHAR(length=20),
            type_=sa.String(length=10),
            nullable=False,
        )
        batch_op.alter_column(
            "id_number",
            existing_type=sa.VARCHAR(length=20),
            type_=sa.String(length=10),
            existing_nullable=False,
        )

    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.alter_column(
            "email",
            existing_type=sa.VARCHAR(length=120),
            type_=sa.String(length=100),
            existing_nullable=False,
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.alter_column(
            "email",
            existing_type=sa.String(length=100),
            type_=sa.VARCHAR(length=120),
            existing_nullable=False,
        )

    with op.batch_alter_table("profile", schema=None) as batch_op:
        batch_op.alter_column(
            "id_number",
            existing_type=sa.String(length=10),
            type_=sa.VARCHAR(length=20),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "phone_number",
            existing_type=sa.String(length=10),
            type_=sa.VARCHAR(length=20),
            nullable=True,
        )

    # ### end Alembic commands ###
